### ISSUE TITLE
Test failure under Python 3.10

### ISSUE THREAD

**Issue by edsu** [webrecorder/py-wacz#20]
I'm noticing a lot of test failures when running the tests under Python3.10 (OS X). Just glancing at the many errors they seem to be all related to `BadZipFile` exceptions that is encountered during test setup `setupClass`? I did some testing and it appears that WACZs created with Python3.10 cannot be read by either python3.10 or python3.9? *Clarification: I noticed the problem when examining the WACZ that was created in the test*.

[output.txt](https://github.com/webrecorder/py-wacz/files/8496632/output.txt)

I also noticed that the wacz files created by the `tests/test_create_wacz.py` differ in size between 3.9 and 3.10 (3.10 is 422 bytes less than 3.9). Maybe there is a timing issue 

```
$ ls -l test*.wacz
-rw-r--r--  1 edsummers  staff  4121 Apr 15 11:31 test-3.10.wacz
-rw-r--r--  1 edsummers  staff  4543 Apr 15 11:30 test-3.9.wacz
```

Looking at the difference with dhex seems to show that information is truncated from the end? Maybe the file isn't being flushed before closing?

<img width="1539" alt="Screen Shot 2022-04-15 at 11 42 47 AM" src="https://user-images.githubusercontent.com/33829/163591477-4a726a5f-6214-47a1-a52a-62c86563ed8f.png">

**Comment by edsu** [comment]
Maybe this is something unique to the test suite, since I appear to be able to `create` and `validate` WACZ files just fine with Python3.10 and they are readable as with the zipfile module.

**Comment by ikreymer** [comment]
very odd. is this mac specific? can try adding a CI runner for python 3.10, and see if that works?

**Comment by edsu** [comment]
Yes, I thought it was odd too. It could be specific to my machine since it seemed like a timing issue related to data being flushed to disk or not?
