### ISSUE TITLE
Detecting pages

### ISSUE THREAD

**Issue by Natkeeran** [webrecorder/py-wacz#36]
We converted a WARC file to WACZ, and it did not detect any pages.  The url based UI is not as user friendly.  

Is there any configuration we can provide to help it detect pages.  Or is there any post-processing we can do to identify the pages?

**Comment by Shrinks99** [comment]
Hey there, without the WARC file or additional details about the command you ran it's a little tricky to nail down the problem.

Generally, the command I use to convert WARCs to WACZ files with a full text and URL index (searchable pages & page detection) is:

```shell
wacz create -f filename.warc -o filename.wacz -t --detect-pages
```

If you don't use `--detect-pages` they won't be detected, if you don't use `-t` the text index will not be generated, and also if you _only_ use `-t` without `--detect pages` the text index won't be generated.

If the above is what you've done and it's still unsuccessful, there may be a bug to look into!  More details about your files would be appreciated so I can try to reproduce them!

> The url based UI is not as user friendly.

I assume this is referring to [ReplayWebpage](https://replayweb.page/)?  If yes, this is something I'm working on right now! :)

**Comment by Natkeeran** [comment]
Thank you for the response and the clarification.  --detect-pages helped.  

Yes, we are using ReplayWebpage.
